<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 style="color:gray"><b>CONFIGURACIÓN DE ARCHIVOS</b>
                    </h1>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-3 col-6">
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>#1</h3>
                            <p>Archivos globales</p>
                        </div>
                        <div class="icon">
                            <i class="fa-solid fa-file-contract fa-fade" style="--fa-animation-duration: 6s;"></i>
                        </div>
                        <a href="<?php echo BASE_URL ?>conarchivos/archivos" class="small-box-footer">Configurar...&nbsp;&nbsp;<i class="fas fa-arrow-circle-right fa-beat-fade"></i>
                        </a>
                    </div>
                </div>

                <div class="col-lg-3 col-6">
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>#2</h3>
                            <p>Documentos</p>
                        </div>
                        <div class="icon">
                            <i class="fa-solid fa-folder-tree fa-fade" style="--fa-animation-duration: 6s;"></i>
                        </div>
                        <a href="<?php echo BASE_URL ?>conarchivos/legajo" class="small-box-footer">Configurar...&nbsp;&nbsp;<i class="fas fa-arrow-circle-right fa-beat-fade"></i>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </section>

</div>