<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 style="color:gray"><b>
              <?php foreach ($_SESSION['submenus'] as $menu) { ?>
                <?php if ($this->_controlador == $menu['v_link']) {
                  echo strtoupper($menu['v_nombre']);
                } else {
                  '';
                } ?>
              <?php } ?></b>
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <section class="col-lg-12 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fa-solid fa-cake-candles"></i>
                &nbsp;<strong>NOTIFICACION CUMPLEAÑOS</strong>
              </h3>
            </div>

            <div class="card-body">
              <div class="row">

                <div class="col-sm-3">
                  <div class="form-group">
                    <button id="btnimgcumple" type="button" class="btn btn-info btn-block"><i class="fas fa-image"></i>&nbsp;&nbsp;<b>AGREGAR IMAGEN</b></button>
                  </div>
                </div>

                <div class="col-sm-12">
                  <table id="tbcumple" class="table table-bordered table-bordered">
                    <thead>
                      <tr class="text-center">
                        <th>ID</th>
                        <th>NOMBRE</th>
                        <th>CONDICION</th>
                        <th>ESTADO</th>
                        <th>VENTANA</th>
                        <th># IMAGEN</th>
                        <th># TEXTO</th>
                        <th>#</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if (isset($this->notificumpleanios)) { ?>
                        <?php foreach ($this->notificumpleanios as $da) { ?>
                          <tr>
                            <td class="text-center" style="vertical-align:middle;"><?php echo $da['i_id'] ?></td>
                            <td class="text-left" style="vertical-align:middle;"><?php echo $da['v_nombre'] ?></td>
                            <td class="text-left" style="vertical-align:middle;"><?php echo $da['v_condicion'] ?></td>
                            <td class="text-center" style="vertical-align:middle;"><span class='badge bg-<?php echo $da['v_color_estado'] ?>'><?php echo $da['v_estado'] ?></span></td>
                            <td class='text-center'>
                              <a href="<?php echo BASE_URL . $da['v_ventana'] ?>" class='btn btn-<?php echo $da['v_color_icon'] ?> btn-sm' target="_blanker"><i class='<?php echo $da['v_icon'] ?>'></i></a>
                            </td>
                            <td class='text-center' style="vertical-align:middle;">
                              <a id='<?php echo $da['i_id'] ?>' style="display: <?php echo $da['v_none_imagen'] ?>;" href="#" class='btn btn-kimbo btn-sm act-datos'><i class='fa fa-edit'></i></a>
                            </td>
                            <td class='text-center' style="vertical-align:middle;">
                              <a id='<?php echo $da['i_id'] ?>' style="display: <?php echo $da['v_none_texto'] ?>;" href="#" class='btn btn-kimbo btn-sm act-cumple'><i class='fa fa-edit'></i></a>
                            </td>
                            <td class='text-center' style="vertical-align:middle;">
                              <a id='<?php echo $da['i_id'] ?>' nombre="<?php echo $da['v_nombre'] ?>" href="#" class='btn btn-danger btn-sm del-cumple'><i class='fa fa-trash-alt'></i></a>
                            </td>
                          </tr>
                        <?php } ?>
                      <?php } ?>
                    </tbody>
                  </table>
                </div>

              </div>
            </div>

          </div>

        </section>
      </div>
    </div>
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <section class="col-lg-12 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-bell"></i>
                &nbsp;<strong>MANTENIMIENTO DE NOTIFICACIONES</strong>
              </h3>
            </div>

            <div class="card-body">
              <div class="row">

                <div class="col-sm-4">
                  <div class="form-group">
                    <button type="button" id="btn-agregar" class="btn btn-success btn-block"><i class="fas fa-plus-circle"></i>&nbsp;&nbsp;<b>CREAR NOTIFICACIÓN</b></button>
                  </div>
                </div>

                <div class="col-sm-12">
                  <table id="example1" class="table table-bordered table-bordered">
                    <thead>
                      <tr class="text-center">
                        <th>ID</th>
                        <th>COLOR</th>
                        <th>TÍTULO</th>
                        <th>SUB TÍTULO</th>
                        <th>CUERPO NOTIFICACIÓN</th>
                        <th>DESCRIPCIÓN NOTIFICACIÓN</th>
                        <th>MODULO</th>
                        <th>ESTADO</th>
                        <th>F. REGISTRO</th>
                        <th>F. ACTUALIZA</th>
                        <th>#</th>
                        <th>#</th>
                        <th>#</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php echo $this->filas ?>
                    </tbody>
                  </table>
                </div>

              </div>
            </div>

          </div>

        </section>
      </div>
    </div>
  </section>

</div>

<!-- MODAL AGREGAR NOTIFICACION-->
<div class="modal fade" id="modal-agregar" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>REGISTRAR NUEVA ZONA</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>COLOR:&nbsp;&nbsp;</label><i class="fas fa-square" style="color:white"></i>
              <select id="color" class="form-control">
                <option value="0" selected disabled>-- SELECCIONE --</option>
                <option value="bg-primary">AZUL</option>
                <option value="bg-secondary">GRISS</option>
                <option value="bg-success">VERDE</option>
                <option value="bg-warning">AMARILLO</option>
                <option value="bg-info">CIAN</option>
                <option value="bg-danger">ROJO</option>
                <option value="bg-light">BLANCO</option>
                <option value="bg-dark">NEGRO</option>
              </select>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="form-group">
              <label>TÍTULO:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="titulo" type="text" class="form-control" autocomplete="off">
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>MENSAJE:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="mensaje" type="text" class="form-control" autocomplete="off" 4>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-12">
            <label class="form-label font-weight-bolder">DESCRIPCIÓN:</label>
            <textarea class="form-control" maxlength="1200" id="descripcion" onpaste="caracteres_descripcion();" onkeyup="caracteres_descripcion();" rows="5" placeholder="escribir breve descripción..." autocomplete="off"></textarea>
            <div class="text" id="res">
              <p><b>0 caractere/s, te quedan 1200</b></p>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label>MODULO:</label>
              <select id="modulo" class="form-control">
                <option value="0" selected disabled>-- SELECCIONE --</option>
                <?php foreach ($this->menunotificacion as $gsm) { ?>
                  <option value="<?php echo $gsm['v_link']; ?>"><?php echo $gsm['v_nombre']; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-registrar" type="button" class="btn btn-success btn-block"><b>REGISTRAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-agregar" type="button" class="btn btn-danger btn-block"><b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL NOTIFICACION EDITAR-->
<div class="modal fade" id="modal-editar" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>ACTUALIZAR NOTIFICACION</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-sm-1">
            <div class="form-group">
              <label>ID:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="codigo1" type="text" class="form-control">
              </div>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <label>COLOR:&nbsp;&nbsp;</label><i class="fas fa-square" style="color:white"></i>
              <select id="color1" class="form-control">
                <option value="0" selected disabled>-- SELECCIONE --</option>
                <option value="bg-primary">AZUL</option>
                <option value="bg-secondary">GRISS</option>
                <option value="bg-success">VERDE</option>
                <option value="bg-warning">AMARILLO</option>
                <option value="bg-info">CIAN</option>
                <option value="bg-danger">ROJO</option>
                <option value="bg-light">BLANCO</option>
                <option value="bg-dark">NEGRO</option>
              </select>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="form-group">
              <label>TÍTULO:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="titulo1" type="text" class="form-control" autocomplete="off">
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>MENSAJE:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="mensaje1" type="text" class="form-control" autocomplete="off">
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-12">
            <label class="form-label font-weight-bolder">DESCRIPCIÓN:</label>
            <textarea class="form-control" maxlength="1200" id="descripcion1" onpaste="caracteres_descripcion();" onkeyup="caracteres_descripcion();" rows="5" placeholder="escribir breve descripción..." autocomplete="off"></textarea>
            <div class="text" id="res">
              <p><b>0 caractere/s, te quedan 1200</b></p>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label>MODULO:</label>
              <select id="modulo1" class="form-control">
                <option value="0" selected disabled>-- SELECCIONE --</option>
                <?php foreach ($this->menunotificacion as $gsm) { ?>
                  <option value="<?php echo $gsm['v_link']; ?>"><?php echo $gsm['v_nombre']; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-actualizar" type="button" class="btn btn-success btn-block"><b>GUARDAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-actualizar" type="button" class="btn btn-danger btn-block"><b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL AGREGAR NOTIFICACION - CUMPLEAÑOS -->
<div class="modal fade" id="modal-agregar-cumple-img" data-backdrop="static">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><i class='fa fa-image fa-bounce'></i>&nbsp;&nbsp;<b>FORMATO - IMAGEN</b></h4>
        <button id="close-modal-agregar" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>CONDICIÓN:</label>
              <select id="condicion-imagen-cumple" class="form-control">
                <option value="0" selected>-- SELECCIONE --</option>
                <option value="1">Ventana + Imagen</option>
                <option value="2">Descargar Imagen</option>
                <option value="3">Ventana + Imagen + Texto</option>
              </select>
            </div>
          </div>
          <div class="col-sm-5">
            <div class="form-group">
              <label>NOMBRE:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="nombre-imagen-cumple" type="text" class="form-control" maxlength="30" placeholder="max. 30 caracteres" autocomplete="off">
              </div>
            </div>
          </div>

          <div class="col-sm-3">
            <div class="form-group">
              <label>ESTADO:</label>
              <select id="estado-imagen-cumple" class="form-control">
                <option value="0" selected>INACTIVO</option>
                <option value="1">ACTIVO</option>
              </select>
            </div>
          </div>
        </div>

        <div class="row">
          <section class="col-lg-6 connectedSortable">

            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <label>IMAGEN:</label>
                  <div class="row">
                    <div class="form-group col-sm-12">
                      <div class="input-group">
                        <input id="imagen-ventana" name="imagen" type="file" accept=".png,.jpg,.jpeg">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>IMAGEN SELECCIONADA:</label>
                  <div class="row">
                    <div class="form-group col-sm-12">
                      <div class="input-group">
                        <img id="preview-imagen-ventana" class="card-img-top" style="border:1px solid black; -webkit-border-radius: 10px;" src="<?php echo BASE_URL ?>public/dist/img/cumpleanios/ventana-no-disponible.jpg">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </section>
        </div>


        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btnagregar-cumple-imagen" type="button" class="btn btn-success btn-block"><b>GUARDAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btncancelar-cumple-imagen" type="button" class="btn btn-danger btn-block"><b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL EDITAR DATOS CONVENIO + IMAGENES -->
<div class="modal fade" id="modal-editar-cumple-img" data-backdrop="static">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><i class='fa fa-edit fa-bounce'></i>&nbsp;&nbsp;<b>EDITAR CONVENIO - IMAGEN</b></h4>
        <button id="close-modal-datos" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-sm-1">
            <div class="form-group">
              <label>ID:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="id-imagen-cumple1" type="text" class="form-control" autocomplete="off">
              </div>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <label>CONDICIÓN:</label>
              <select id="condicion-imagen-cumple1" class="form-control">
                <option value="0" selected>-- SELECCIONE --</option>
                <option value="1">Ventana + Imagen</option>
                <option value="2">Descargar Imagen</option>
                <option value="3">Ventana + Imagen + Texto</option>
              </select>
            </div>
          </div>
          <div class="col-sm-5">
            <div class="form-group">
              <label>NOMBRE:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="nombre-imagen-cumple1" type="text" class="form-control" maxlength="30" placeholder="max. 30 caracteres" autocomplete="off">
              </div>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <label>ESTADO:</label>
              <select id="estado-imagen-cumple1" class="form-control">
                <option value="0" selected>INACTIVO</option>
                <option value="1">ACTIVO</option>
              </select>
            </div>
          </div>
        </div>

        <div class="row">
          <section class="col-lg-6 connectedSortable">

            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <label>IMAGEN EN VENTANA:</label>
                  <div class="row">
                    <div class="form-group col-sm-12">
                      <div class="input-group">
                        <input id="imagen-ventana1" name="imagen" type="file" accept=".png,.jpg,.jpeg">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>IMAGEN SELECCIONADA:</label>
                  <div class="row">
                    <div class="form-group col-sm-12">
                      <div id="draw-ventana1" style='border-radius: 10px; -webkit-border-radius: 10px;'>
                        <img id="ruta-imagen-ventana1" class="card-img-top" style="border:1px solid black; -webkit-border-radius: 10px;" src="<?php echo BASE_URL ?>public/dist/img/cumpleanios/ventana-no-disponible.jpg">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </section>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btnagregar-cumple-imagen1" type="button" class="btn btn-success btn-block"><b>GUARDAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btncancelar-cumple-imagen1" type="button" class="btn btn-danger btn-block"><b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL EDITAR CONVENIO - IMAGEN + TEXTO -->
<div class="modal fade" id="modal-editar-cumple" data-backdrop="static">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><i class="fa fa-edit fa-bounce"></i><b>&nbsp;&nbsp;ACTUALIZAR SALUDO CUMPLEAÑOS</b></h4>
        <button id="close-modal-disenio" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="row">
            <div class="col-md-12 col-6">
              <div class="form-group">
                <p><b><mark>* Se especifica que existen variables globales en el sistema, las cuales pueden ser de su uso. <a class="modal-global" href="#">click aqui</a></b></p>
              </div>
            </div>
          </div>
          <section class="col-lg-6 connectedSortable">
            <div class="col-md-12">
              <div class="form-group">
                <div id="draw-img" style="border-radius: 10px; -webkit-border-radius: 10px;">
                </div>
              </div>
            </div>
          </section>
          <section class="col-lg-6 connectedSortable">
            <div class="row">
              <div class="col-md-12 col-6">
                <button id="btn-refresh" type="button" class="btn btn-warning btn-block"><i class="fa-solid fa-arrows-rotate fa-spin"></i><b>&nbsp;&nbsp;Refrescar imagen</b></button>
              </div>
            </div>
            <div class="row">

              <div class="form-group col-sm-6">
                <label>ID:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="letraid" type="text" class="form-control">
                </div>
              </div>

              <div class="form-group col-sm-6">
                <label>IDCUMPLE:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="cumpleid" type="text" class="form-control">
                </div>
              </div>

            </div>
            <div class="row">

              <div class="form-group col-sm-12">
                <label>TEXTO:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="letrastext" type="text" class="form-control" autocomplete="off" placeholder="ingrese el texto...">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-sm-3">
                <label>TAMAÑO:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="letrasize" type="number" class="form-control" value="10" min="0" max="100">
                </div>
              </div>

              <div class="form-group col-sm-3">
                <label>COLOR:</label>
                <div class="input-group ql-color-picker">
                  <input id="letracolor" type="color" class="form-control" value="#000000">
                </div>
              </div>

              <div class="form-group col-sm-3">
                <label>ANGULO:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="letraangle" type="number" class="form-control" value="0" min="0">
                </div>
              </div>

              <div class="form-group col-sm-3">
                <label>ALINEACIÓN:</label>
                <select id="textalign" class="form-control">
                  <option value="0" selected>Ninguno</option>
                  <option value="1">Centrado</option>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-sm-3">
                <label>POSICION X:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="letrax" type="number" class="form-control" value="0" min="0">
                </div>
              </div>

              <div class="form-group col-sm-3">
                <label>POSICION Y:</label>
                <div class="input-group" data-target-input="nearest">
                  <input id="letray" type="number" class="form-control" value="0" min="0">
                </div>
              </div>

              <div class="form-group col-sm-6">
                <label>TIPOGRAFÍA:</label>
                <select id="textfont" class="form-control">
                  <option value="Arial" style="font-family: Arialn">Arial</option>
                  <option value="Arialb" style="font-family: Arialb">Arial Bold</option>
                  <option value="GOTHIC" style="font-family: GOTHIC">Century Gothic</option>
                  <option value="GOTHICB" style="font-family: GOTHICB">Century Gothic Bold</option>
                  <option value="ComicSans" style="font-family: ComicSans">Comic Sans Serif</option>
                  <option value="ComicSansb" style="font-family: ComicSansb">Comic Sans Serif Bold</option>
                  <option value="DancingScript" style="font-family: DancingScript">Dancing Script</option>
                  <option value="DancingScriptb" style="font-family: DancingScriptb">Dancing Script SemiBold</option>
                  <option value="Orkney" style="font-family: Orkney">Orkney</option>
                  <option value="OrkneyB" style="font-family: Orkneyb">Orkney Bold</option>
                  <option value="SegoePrint" style="font-family: SegoePrint">Segoe Print</option>
                  <option value="SegoePrintB" style="font-family: SegoePrintb">Segoe Print Bold</option>
                  <option value="Timesnew" style="font-family: timesnew">Times New Roman</option>
                  <option value="TimesnewB" style="font-family: timesnewb">Times New Roman Bold</option>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-6">
                <button id="btn-agregar-disenio" type="button" class="btn btn-success btn-block"><b><i class="fa-solid fa-save fa-beat"></i>&nbsp;&nbsp;Guardar diseño</b></button>
              </div>
              <div class="col-md-6 col-6">
                <button id="btn-limpiar-disenio" type="button" class="btn btn-danger btn-block"><b><i class="fa-solid fa-brush fa-beat"></i>&nbsp;&nbsp;Limpiar diseño</b></button>
              </div>
            </div>
          </section>
        </div>
        <section class="col-lg-12 connectedSortable">
          <div class="row">
            <div class="col-md-12 col-12">
              <br>
              <table id="example" class="table table-bordered">
                <thead>
                  <tr class="text-center">
                    <th># ID</th>
                    <th>IDCUMPLE</th>
                    <th>TEXTO</th>
                    <th>TAMAÑO</th>
                    <th>COLOR</th>
                    <th>ANGULO</th>
                    <th>X</th>
                    <th>Y</th>
                    <th>ALINEACION</th>
                    <th>FUENTE</th>
                    <th>#</th>
                    <th>#</th>
                  </tr>
                </thead>
                <tbody id="tbdisenioimg" class="text-center">
                </tbody>
              </table>
            </div>
          </div>
        </section>
        <div class="form-group">
          <div class="row">
            <div class="col-md-6 col-6">
              <button id="btn-cancelar-disenio" type="button" class="btn btn-danger btn-block"><b>Cancelar</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL GLOBAL -->
<div class="modal fade" id="modal-variable-global" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><i class="fa fa-edit"></i><b>&nbsp;&nbsp;VARIABLES GLOBALES DEL SISTEMA</b></h4>
        <button id="close-modal-disenio" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 col-6">
            <div class="form-group">
              <p>Considerar el texto resaltado, incluyendo los corchetes: <mark>[variable]</mark>:</p>
              <br>
              <p><mark><b>[ruc]</b></mark> => RUC de la empresa. Ejm: "<b><?php echo ruc ?></b>".</p>
              <p><mark><b>[razon]</b></mark> => Razon social de la empresa. Ejm: "<b><?php echo $_SESSION['razon'] ?></b>".</p>
              <p><mark><b>[nombrecomercial]</b></mark> => Nombre comercial de la empresa. Ejm: "<b><?php echo nombrecomercial ?></b>".</p>
              <br>
              <p><mark><b>[perfil]</b></mark> => Perfil del usuario logueado. Ejm: uds tiene el usuario "<b><?php echo $_SESSION['perfil'] ?></b>.</p>
              <p><mark><b>[dni]</b></mark> => Documento de identidad del usuario logueado. Ejm: <b><?php echo $_SESSION['dni'] ?></b>.</p>
              <p><mark><b>[usuario]</b></mark> => Primer nombre y Primer apellido del usuario logueado. Ejm: <b><?php echo $_SESSION['usuario'] ?></b>.</p>
              <p><mark><b>[nombre]</b></mark> => Nombres y Apellidos completos del usuario logueado. Ejm: <b><?php echo $_SESSION['nombre'] ?></b>.</p>
              <p><mark><b>[nombres]</b></mark> => Nombres completos del usuario logueado. Ejm: <b><?php echo $_SESSION['nombres'] ?></b>.</p>
              <p><mark><b>[apellidos]</b></mark> => Apellidos completos del usuario logueado. Ejm: <b><?php echo $_SESSION['apellidos'] ?></b>.</p>
              <br>
              <p><mark><b>[fecha]</b></mark> => Fecha actual del sistema. Ejm: fecha de hoy "<b><?php echo fechasis ?></b>".</p>
              <p><mark><b>[fechahora]</b></mark> => Fecha y hora actual del sistema. Ejm: La fecha y hora actual es "<b><?php echo fechahorasis ?></b>"</p>
              <p><mark><b>[cargo]</b></mark> => Cargo del personal en la Empresa. Ejm: Tu cargo actual es "<b><?php echo $_SESSION['cargo'] ?></b>"</p>
              <br>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-6 col-6">
              <button id="btn-cancelar-global" type="button" class="btn btn-danger btn-block"><b>Salir</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>