<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
          <h1 style="color:gray"><b>
            <?php foreach ($_SESSION['submenus'] as $menu) { ?>
              <?php if ($this->_controlador == $menu['v_link']) {
                echo strtoupper($menu['v_nombre']);
              } else {
                '';
              } ?>
            <?php } ?></b>
          </h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">

    <div class="container-fluid">

      <div class="row">

        <section class="col-lg-6 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-file-pdf"></i>
                &nbsp;<strong>DESCARGA DE BOLETAS DE PAGO</strong>
              </h3>
              <div class="card-tools">
              </div>
            </div>
            <input hidden id="ip" name="ip" type="text" class="form-control">

            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr class="text-center">
                    <th>NRO BOLETA</th>
                    <th>AÑO</th>
                    <th>PERIODO</th>
                    <th>SUELDO NETO</th>
                    <th>#</th>
                  </tr>
                </thead>
                <tbody>
                  <?php if (isset($this->boletas)) { ?>
                    <?php foreach ($this->boletas as $bo) { ?>
                      <tr>
                        <td class="text-center"><?php echo $bo['nbrboleta'] ?></td>
                        <td class="text-center"><?php echo $bo['anhio'] ?></td>
                        <td class="text-center"><?php echo $bo['periodoid'] ?></td>
                        <td class="text-center"><?php echo number_format($bo['sneto'], 2) ?></td>
                        <td class="text-center">
                          <a id="<?php echo $bo['nbrboleta'] ?>" href="<?php echo BASE_URL ?>documentospago/boleta/<?php echo $bo['nbrboleta'] ?>" class="btn btn-danger btn-sm bol" target="_blank" style="color:white"><i class="fas fa-file-pdf"></i></a>
                        </td>
                      </tr>
                    <?php } ?>
                  <?php } ?>
                </tbody>
              </table>
            </div>
          </div>

        </section>

        <section class="col-lg-6 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-file-pdf"></i>
                &nbsp;<strong>DESCARGA CERTIFICADO DE UTILIDADES</strong>
              </h3>
              <div class="card-tools">
              </div>
            </div>

            <div class="card-body">
              <table id="example2" class="table table-bordered table-striped">
                <thead>
                  <tr class="text-center">
                    <th>AÑO</th>
                    <th>PERIODO</th>
                    <th>DOCUMENTO</th>
                  </tr>
                </thead>
                <tbody>
                  <?php if (isset($this->certificadouti)) { ?>
                    <?php foreach ($this->certificadouti as $ci) { ?>
                      <tr>
                        <td class="text-center"><?php echo $ci['ANHIO'] ?></td>
                        <td class="text-center"><?php echo $ci['PERIODO'] ?></td>
                        <td class="text-center">
                          <a id="<?php echo $ci['PERIODO']?>" href="<?php echo BASE_URL ?>documentospago/certificadoutilidades/<?php echo $ci['ANHIO'] ?>" class="btn btn-danger btn-sm uti" target="_blank" style="color:white"><i class="fas fa-file-pdf"></i></a>
                        </td>
                      </tr>
                    <?php } ?>
                  <?php } ?>
                </tbody>
              </table>
            </div>
          </div>

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-file-pdf"></i>
                &nbsp;<strong>DESCARGA CERTIFICADO DE CTS SEMESTRAL</strong>
              </h3>
              <div class="card-tools">
              </div>
            </div>

            <div class="card-body">
              <table id="example3" class="table table-bordered table-striped">
                <thead>
                  <tr class="text-center">
                    <th>AÑO</th>
                    <th>PERIODO</th>
                    <th>DOCUMENTO</th>
                  </tr>
                </thead>
                <tbody>
                  <?php if (isset($this->certificadocts)) { ?>
                    <?php foreach ($this->certificadocts as $cts) { ?>
                      <tr>
                        <td class="text-center"><?php echo $cts['ANHIO'] ?></td>
                        <td class="text-center"><?php echo $cts['PERIODO'] ?></td>
                        <td class="text-center">
                          <a id="<?php echo $cts['PERIODO']?>" href="<?php echo BASE_URL ?>documentospago/certificadocts/<?php echo $cts['PERIODO'] ?>" class="btn btn-danger btn-sm cts" target="_blank" style="color:white"><i class="fas fa-file-pdf"></i></a>
                        </td>
                      </tr>
                    <?php } ?>
                  <?php } ?>
                </tbody>
              </table>
            </div>
          </div>

        </section>

      </div>

    </div>

  </section>

</div>