<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
          <h1 style="color:gray"><b>
              <?php foreach ($_SESSION['submenus'] as $menu) { ?>
                <?php if ($this->_controlador == $menu['v_link']) {
                  echo strtoupper($menu['v_nombre']);
                } else {
                  '';
                } ?>
              <?php } ?></b>
          </h1>
        </div>
      </div>
    </div>
  </div>

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <section class="col-lg-6 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-compass"></i>
                &nbsp;<strong>MANTENIMIENTO DE ZONAS</strong>
              </h3>
            </div>

            <div class="card-body">
              <div class="row">

                <div class="col-sm-6">
                  <div class="form-group">
                    <button type="button" id="btn-agregar" class="btn btn-success btn-block"><i class="fas fa-plus-circle"></i>&nbsp;&nbsp;<b>AGREGAR</b></button>
                  </div>
                </div>

                <div class="col-sm-12">
                  <table id="example1" class="table table-bordered table-bordered">
                    <thead>
                      <tr class="text-center">
                        <th>CODIGO</th>
                        <th>ZONA</th>
                        <th>ESTADO</th>
                        <th>#</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if (isset($this->zona)) { ?>
                        <?php foreach ($this->zona as $lc) { ?>
                          <tr>
                            <td class="text-center"><?php echo $lc['i_codigo'] ?></td>
                            <td class="text-left"><?php echo $lc['v_descripcion'] ?></td>
                            <td class="text-center"><span class='badge bg-<?php if ($lc['i_estado'] == 1) {
                                                                            echo 'success';
                                                                          } else {
                                                                            echo 'danger';
                                                                          }; ?>'><?php if ($lc['i_estado'] == 1) {
                                                                                    echo 'ACTIVO';
                                                                                  } else {
                                                                                    echo 'INACTIVO';
                                                                                  }; ?></span></td>
                            <td class='text-center'>
                              <a href="#" id='<?php echo $lc['i_codigo'] ?>' class='btn btn-kimbo btn-sm actualizar'><i class='fa fa-edit'></i></a>
                            </td>
                          </tr>
                        <?php } ?>
                      <?php } ?>
                    </tbody>
                  </table>
                </div>

              </div>
            </div>

          </div>

        </section>
      </div>
    </div>
  </section>

</div>

<!-- MODAL AGREGAR LOCAL-->
<div class="modal fade" id="modal-agregar" data-backdrop="static">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>REGISTRAR NUEVA ZONA</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <!--INGRESO DEL NUEVO LOCAL A CREAR-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>NOMBRE ZONA:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="nombre-zona" type="text" class="form-control" onkeypress='return sololetras(event)' style="text-transform:uppercase;" autocomplete="off">
                <div class="input-group-append" data-target="#nombre-local">
                  <div class="input-group-text"><i class="fa fa-thumbtack"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-registrar" type="button" class="btn btn-success btn-block">
                <i class="fas fa-save"></i>
                &nbsp;&nbsp;<b>REGISTRAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-agregar" type="button" class="btn btn-danger btn-block">
                <i class="fas fa-ban"></i>
                &nbsp;&nbsp;<b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL LOCAL EDITAR-->
<div class="modal fade" id="modal-editar" data-backdrop="static">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>ACTUALIZAR ZONA</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <!--ID DEL LOCAL-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>ID ZONA:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="id-zona-actualizar" type="text" class="form-control">
                <div class="input-group-append" data-target="#id-local-actualizar">
                  <div class="input-group-text"><i class="fa fa-id-badge"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!--NOMBRE DEL LOCAL A ACTUALIZAR-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>NOMBRE ZONA:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="nombre-zona-actualizar" type="text" class="form-control" onkeypress='return sololetras(event)' style="text-transform:uppercase;" autocomplete="off">
                <div class="input-group-append" data-target="#nombre-local-actualizar">
                  <div class="input-group-text"><i class="fa fa-thumbtack"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!--PARA SELECCION DE ESTADO (DEFAULT 1.ACTIVO, 2.INACTIVO)-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>ESTADO:</label>
              <select id="estado-zona-actualizar" class="form-control">
                <option value="0">INACTIVO</option>
                <option value="1">ACTIVO</option>
              </select>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-actualizar" type="button" class="btn btn-success btn-block">
                <i class="fas fa-save"></i>
                &nbsp;&nbsp;<b>GUARDAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-actualizar" type="button" class="btn btn-danger btn-block">
                <i class="fas fa-ban"></i>
                &nbsp;&nbsp;<b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>