<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
                    <h1 style="color:gray"><b>
                            <?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                <?php if ($this->_controlador == $menu['v_link']) {
                                    echo strtoupper($menu['v_nombre']);
                                } else {
                                    '';
                                } ?>
                            <?php } ?></b>
                    </h1>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <section class="col-lg-8">
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 col-12">
                                    <button id="btnperfil" type="button" class="btn btn-success btn-block font-weight-bolder" style="color: White;">
                                        <i class="fas fa-user-plus"></i>
                                        &nbsp;&nbsp;CREAR PERFIL
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead>
                                            <tr class="text-center">
                                                <th># Código</th>
                                                <th>Nombre</th>
                                                <th>Estado</th>
                                                <th>#</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->perfiles)) { ?>
                                                <?php foreach ($this->perfiles as $tr) { ?>
                                                    <tr>
                                                        <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_nombre'] ?></td>
                                                        <td class="text-center"><span class="badge bg-<?php echo $tr['v_color'] ?>"><?php echo $tr['v_estado'] ?></span></td>
                                                        <td class='text-center'>
                                                            <a id="<?php echo $tr['i_id'] ?>" nombre="<?php echo $tr['v_nombre'] ?>" estado="<?php echo $tr['i_estado'] ?>" class="btn btn-warning btn-sm editar" style="color:white">
                                                                <i class="fas fa-edit"></i>
                                                            </a>
                                                        </td>
                                                        <td class='text-center'>
                                                            <a href='<?php echo BASE_URL ?>conperfiles/configuracionperfil/&perfil=<?php echo $tr['i_id'] ?>&nombreperfil=<?php echo $tr['v_nombre'] ?>' class='btn btn-primary btn-sm text-black'>
                                                                <i class='fa fa-cog'></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>

            </div>

        </div>
    </section>

</div>

<!-- MODAL AGREGAR PERFIL-->
<div class="modal fade" id="modal-agregar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">CREAR PERFIL</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Nombre perfil:</label>
                        <input type="text" id="xnombre" tabindex="1" class="form-control" autocomplete="off" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="xbtnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="xbtncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- MODAL EDITAR DATO-->
<div class="modal fade" id="modal-editar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">ACTUALIZAR PERFIL:&nbsp;</h5><b><span id="idtabla"></span></b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Códgo perfil:</label>
                        <input type="text" id="codigo" tabindex="1" class="form-control" autocomplete="off" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Nombre perfil:</label>
                        <input type="text" id="nombre" tabindex="1" class="form-control" autocomplete="off" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Estado:</label>
                        <select id="estado" tabindex="2" class="form-control form-control-md">
                            <option value="0">Inactivo</option>
                            <option value="1">Activo</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="btnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="btncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>