<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon verdum" href="<?php echo BASE_URL ?>public/dist/img/favicon.png" />
  <title>SYSTEM CRM | Inicio de sesión</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo BASE_URL ?>public/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="<?php echo BASE_URL ?>public/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo BASE_URL ?>public/dist/css/adminlte.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- Favicons -->
  <link href="<?php echo BASE_URL ?>public/dist/img/favicon.png" rel="icon">

</head>

<body class="hold-transition login-page" background="<?php echo BASE_URL ?>public/dist/img/fondo.jpg">
  <!-- <body class="hold-transition login-page"> -->
  <div class="login-box">
    <div class="login-logo">
      <b style="color:white; background-color: transparent"><strong>SYSTEM CRM</strong></b>
    </div>
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">

        <form role="form">
          <div class="input-group mb-3">
            <input type="text" class="form-control" id="usuario" placeholder="Usuario" tabindex="1" autocomplete="off">
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-user"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <input type="password" class="form-control" id="password" onkeypress="pulsar(event)" tabindex="2" placeholder="Password">
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          <div class="row">

            <div class="col-12">
              <button type="button" id="btn_login" class="btn btn-success btn-block"><b>Ingresar</b></button>
              <div id="msj"></div>
            </div>

          </div>
        </form>

        <div class="social-auth-links text-center mb-3">

        </div>
        <p class="text-center mt-2">
          <span>Olvidastes tu clave?</span>
          <a href="<?php echo BASE_URL ?>index/recupera_clave">Recuperar mi clave</a>
        </p>
      </div>
      <!-- /.login-card-body -->
    </div>
  </div>
  <!-- /.login-box -->

  <!-- jQuery -->
  <script src="<?php echo BASE_URL ?>public/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="<?php echo BASE_URL ?>public/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="<?php echo BASE_URL ?>public/dist/js/adminlte.min.js"></script>

  <?php if (isset($_layoutParams['js']) && count($_layoutParams['js'])) : ?>
    <?php foreach ($_layoutParams['js'] as $layout) : ?>
      <script src="<?php echo  $layout ?>" type="text/javascript"></script>
    <?php endforeach; ?>
  <?php endif; ?>

</body>

</html>