<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>VERDUM | Registro</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo BASE_URL?>public/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="<?php echo BASE_URL?>public/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo BASE_URL?>public/dist/css/adminlte.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <strong>VERDUM PERU SAC</strong>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <!-- <p class="login-box-msg">Register a new membership</p> -->

      <form role="form">
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="dni" placeholder="DNI" autocomplete="off">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="email" class="form-control" id="email" placeholder="Email" autocomplete="off">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <!-- /.col -->
          <div class="col-12">
            <button type="button" id="btn_registrar" class="btn btn-primary btn-block">Registrar</button>
          </div>
          <!-- /.col -->    
         
        </div>
       
            <div class="row">
                <div class="col-12 mt-3">
                    <div class="msj"></div>
                </div>
            </div>
        
       
      </form>

      <div class="social-auth-links text-center">
      
      </div>

      <a href="<?php echo BASE_URL?>index/login" class="text-center">Iniciar sesión</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="<?php echo BASE_URL?>public/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?php echo BASE_URL?>public/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo BASE_URL?>public/dist/js/adminlte.min.js"></script>

<?php if(isset($_layoutParams['js']) && count($_layoutParams['js'])): ?>
<?php foreach($_layoutParams['js'] as $layout): ?>
<script src="<?php echo  $layout ?>" type="text/javascript"></script> 
<?php endforeach; ?>
<?php endif; ?>



<!-- MODAL DETALLE-->
<div class="modal fade" id="modal-activacion">
        <div class="modal-dialog modal-md">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Activacion de registro</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

                  <div class="form-group">
                    <label for="codigo">Codigo de Activacion</label>
                    <input id="codigo" type="text" class="form-control" >
                  </div>
                 
                <div class="form-group">
                  <button type="button" id="btn_activar" class="btn btn-primary btn-block" >Activar</button>
                  <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
                
                  <div id="mensaje"></div>

            </div>
            
            
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      <!-- /.modal -->
</div>


</body>
</html>



