<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 style="color:gray"><b>Notificaciones - Línea de tiempo</b>
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- /.content-header -->
  <section class="content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-md-12">

          <div class="timeline">

            <?php echo $this->timeline ?>

            <div>
              <i class="fas fa-clock bg-gray"></i>
            </div>

          </div>

        </div>
      </div>
    </div>

  </section>


</div>