<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
                    <h1 style="color:gray"><b>
                            <?php foreach ($_SESSION['menus'] as $menu) { ?>
                                <?php if ($this->_controlador == $menu['v_link']) {
                                    echo strtoupper(str_replace("&ntilde;","Ñ",$menu['v_nombre']));
                                } else {
                                    '';
                                } ?>
                            <?php } ?></b>
                    </h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">

        <div class="container-fluid">

            <div class="row">

                <!-- calendario -->
                <section class="col-lg-12 connectedSortable">

                    <div class="card card-gray">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fas fa-birthday-cake"></i>
                                &nbsp;<strong>CUMPLEAÑOS</strong>
                            </h3>
                        </div>
                        <div class="card-body">
                            <div id="calendar">
                            </div>
                        </div>
                    </div>

                </section>

            </div>

        </div>

    </section>

</div>