    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
                        <h1 style="color:gray"><b>EVALUACIÓN</b>
                        </h1>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <section class="col-lg-12 connectedSortable">

                        <div class="card card-gray">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <i class="fa-solid fa-book-open-reader"></i>
                                    &nbsp;<strong>EVALUACIONES ANUALES</strong>
                                </h3>
                            </div>

                            <div class="card-body">
                                <div class="row">

                                    <div class="col-sm-12">
                                        <table id="example1" class="table table-bordered table-bordered">
                                            <thead>
                                                <tr class="text-center">
                                                    <th>#ID</th>
                                                    <th>DNI</th>
                                                    <th>NOMBRES Y APELLIDOS</th>
                                                    <th>AÑO</th>
                                                    <th>AREA</th>
                                                    <th>CARGO</th>
                                                    <th>TIPO CARGO</th>
                                                    <th>PAIS</th>
                                                    <th>SEDE</th>
                                                    <th>JEFATURA</th>
                                                    <th><i data-feather='settings'></i> PDF</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php if (isset($this->ListadoEvaluacion)) { ?>
                                                    <?php foreach ($this->ListadoEvaluacion as $ac) { ?>
                                                        <tr>
                                                            <td class="text-center"><?php echo $ac['i_id'] ?></td>
                                                            <td class="text-center"><?php echo $ac['v_dni'] ?></td>
                                                            <td class="text-left"><?php echo $ac['v_nombre'] ?></td>
                                                            <td class="text-center"><?php echo $ac['i_anhio'] ?></td>
                                                            <td class="text-left"><?php echo $ac['v_area'] ?></td>
                                                            <td class="text-left"><?php echo $ac['v_cargo'] ?></td>
                                                            <td class="text-left"><?php echo $ac['v_tipo_cargo'] ?></td>
                                                            <td class="text-center"><?php echo $ac['v_zona_pais'] ?></td>
                                                            <td class="text-center"><?php echo $ac['v_sede'] ?></td>
                                                            <td class="text-center"><?php echo $ac['v_jefe'] ?></td>
                                                            <td class='text-center'>
                                                                <a href="<?php echo BASE_URL ?>evaluacionpersona/ver_pdf_evaluacion/&dni=<?php echo $ac['v_dni'] ?>&anhio=<?php echo $ac['i_anhio']?>" class="btn btn-danger btn-sm bol" target="_blank" style="color:white"><i class="fas fa-file-pdf fa-beat"></i></a>
                                                            </td>
                                                        </tr>
                                                    <?php } ?>
                                                <?php } ?>
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>

                        </div>

                    </section>
                </div>
            </div>
        </section>

    </div>