<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
          <h1 style="color:gray"><b>
              <?php foreach ($_SESSION['submenus'] as $menu) { ?>
                <?php if ($this->_controlador == $menu['v_link']) {
                  echo strtoupper($menu['v_nombre']);
                } else {
                  '';
                } ?>
              <?php } ?></b>
          </h1>
        </div>
      </div>
    </div>
  </div>

  <section class="content">
    <div class="container-fluid">
      <div class="row">

        <section class="col-lg-12 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fas fa-calendar"></i>
                &nbsp;<strong>CREACION DE SEMANA</strong>
              </h3>
            </div>


            <div class="card-body">
              <div class="row">

                <div class="col-sm-4">
                  <div class="form-group">
                    <button type="button" id="btn-agregar" class="btn btn-success btn-block"><i class="fas fa-plus-circle"></i>&nbsp;&nbsp;<b>CREAR SEMANA</b></button>
                  </div>
                </div>

                <div class="col-sm-12">
                  <table id="example1" class="row-border hover order-column table-bordered">
                    <thead>
                      <tr class="text-center">
                        <th>ID</th>
                        <th>SEMANA</th>
                        <th>DESCRIPCION</th>
                        <th>LOCAL</th>
                        <th>AÑO</th>
                        <th>DIAS</th>
                        <th>#</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if (isset($this->turnos)) { ?>
                        <?php foreach ($this->turnos as $tr) { ?>
                          <tr>
                            <td class="text-center"><?php echo $tr['i_id'] ?></td>
                            <td class="text-center"><?php echo $tr['i_num_semana'] ?></td>
                            <td class="text-center"><?php echo $tr['v_descripcion'] ?></td>
                            <td class="text-center"><span class="badge bg-success"><?php echo $tr['v_local'] ?></span></td>
                            <td class="text-center"><?php echo $tr['i_anhio'] ?></td>
                            <td class="text-center"><?php echo $tr['i_dias'] ?></td>
                            <td class='text-center'>
                              <a href='<?php echo BASE_URL ?>turnos/detalle_turnos/&semana=<?php echo $tr['i_num_semana'] ?>&descripcion=<?php echo $tr['v_descripcion'] ?>&idsemana=<?php echo $tr['i_id'] ?>&idlocal=<?php echo $tr['id_local'] ?>&anhio=<?php echo $tr['i_anhio'] ?>' class='btn btn-kimbo btn-sm text-black'><i class='fa fa-eye'></i></a>
                            </td>
                          </tr>
                        <?php } ?>
                      <?php } ?>
                    </tbody>
                  </table>
                </div>

              </div>
            </div>

          </div>

        </section>

      </div>
    </div>
  </section>
</div>

<!-- MODAL AGREGAR LOCAL-->
<div class="modal fade" id="modal-agregar" data-backdrop="static">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>REGISTRAR SEMANA</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <!--ELEGIR SEMANA-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>ELEGIR SEMANA</label>
              <select id="semana" class="form-control select2bs4">
                <?php foreach ($this->semana as $pr) { ?>
                  <option value="<?php echo $pr['i_num_semana']; ?>" <?php echo $pr['i_select']; ?>>(semana <?php echo $pr['i_num_semana']; ?>) <?php echo $pr['v_descripcion']; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </div>

        <div class="row">
          <!--PARA SELECCION DE LOCAL-->
          <div class="col-sm-12">
            <div class="form-group">
              <label>ELEGIR LOCAL:</label>
              <select id="local" class="form-control">
                <?php foreach ($this->local as $gc) { ?>
                  <option value="<?php echo $gc['i_codigo']; ?>"><?php echo $gc['v_descripcion']; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-registrar" type="button" class="btn btn-success btn-block">
                <i class="fas fa-save"></i>
                &nbsp;&nbsp;<b>Registrar</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-agregar" type="button" class="btn btn-danger btn-block">
                <i class="fas fa-ban"></i>
                &nbsp;&nbsp;<b>Cancelar</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>