<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 style="color:gray"><b>
              <?php foreach ($_SESSION['submenus'] as $menu) { ?>
                <?php if ($this->_controlador == $menu['v_link']) {
                  echo strtoupper($menu['v_nombre']);
                } else {
                  '';
                } ?>
              <?php } ?></b>
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <section class="col-lg-12 connectedSortable">

          <div class="card card-gray">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-compass"></i>
                &nbsp;<strong>MANTENIMIENTO DE INVENTARIO PARA VENTAS AL PERSONAL</strong>
              </h3>
            </div>

            <div class="card-body">
              <div class="row">

                <div class="col-sm-4">
                  <div class="form-group">
                    <button type="button" id="btn-agregar" class="btn btn-success btn-block"><i class="fas fa-plus-circle"></i>&nbsp;&nbsp;<b>AGREGAR ARTICULO</b></button>
                  </div>
                </div>

                <div class="col-sm-12">
                  <table id="example1" class="table table-bordered table-bordered">
                    <thead>
                      <tr class="text-center">
                        <th>ID</th>
                        <th>SKU</th>
                        <th>DESCRIPCION</th>
                        <th>MARCA</th>
                        <th>PRECIO (S/)</th>
                        <th>ESTADO</th>
                        <th>F. REGISTRO</th>
                        <th>F. ACTUALIZA</th>
                        <th>#</th>
                        <th>#</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php echo $this->filas ?>
                    </tbody>
                  </table>
                </div>

              </div>
            </div>

          </div>

        </section>
      </div>
    </div>
  </section>

</div>

<!-- MODAL AGREGAR INVENTARIO-->
<div class="modal fade" id="modal-agregar" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>REGISTRAR NUEVA ZONA</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <!--INGRESO DEL NUEVO LOCAL A CREAR-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>SKU:</label>
              <div class="select2-success">
                <select id="sku" class="select2" multiple="multiple" data-placeholder="Seleccione SKU(s).." data-dropdown-css-class="select2-success" style="width: 100%;">
                  <?php foreach ($this->sku as $sku) { ?>
                    <option value="<?php echo $sku['v_sku']; ?>">(<?php echo $sku['v_sku']; ?>) <?php echo $sku['v_descripcion']; ?></option>
                  <?php } ?>
                </select>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-registrar" type="button" class="btn btn-success btn-block"><b>REGISTRAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-agregar" type="button" class="btn btn-danger btn-block"><b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>

<!-- MODAL INVENTARIO EDITAR-->
<div class="modal fade" id="modal-editar" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title col-11 text-center"><b>ACTUALIZAR INVENTARIO</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <!--ID DEL LOCAL-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>SKU:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="sku1" type="text" class="form-control">
              </div>
            </div>
          </div>
        </div>

        <!--NOMBRE DEL LOCAL A ACTUALIZAR-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>DESCRIPCION:</label>
              <div class="input-group" data-target-input="nearest">
                <input id="descripcion1" type="text" class="form-control" autocomplete="off">
              </div>
            </div>
          </div>
        </div>

        <!--PARA SELECCION DE ESTADO (DEFAULT 1.ACTIVO, 2.INACTIVO)-->
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label>ESTADO:</label>
              <select id="estado1" class="form-control">
                <option value="0">INACTIVO</option>
                <option value="1">ACTIVO</option>
              </select>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <button id="btn-actualizar" type="button" class="btn btn-success btn-block"><b>GUARDAR</b></button>
            </div>
            <div class="col-sm-6">
              <button id="btn-cancelar-actualizar" type="button" class="btn btn-danger btn-block"><b>CANCELAR</b></button>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</div>