<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0 text-dark">RECURSOS HUMANOS | VERDUM PERÚ S.A.C.</h1> -->
                    <h1 style="color:gray"><b>CONFIGURACIÓN DE PERIODOS PARA DOCUMENTOS</b>
                    </h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">

                <section class="col-lg-6 connectedSortable">

                    <div class="card card-gray">

                        <div class="card-header">
                            <h3 class="card-title"><b>PERIODOS PARA BOLETAS MENSUALES</b></h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </div>
                        </div>

                        <div class="card-body">

                            <table id="example1" class="table table-bordered">
                                <thead>
                                    <tr class="text-center">
                                        <th>#</th>
                                        <th>Periodo</th>
                                        <th>Firma</th>
                                        <th>Estado</th>
                                        <th>Usuario</th>
                                        <th>Fecha y hora</th>
                                        <th>#</th>
                                        <th>#</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (isset($this->periodoboletas)) { ?>
                                        <?php foreach ($this->periodoboletas as $tr) { ?>
                                            <tr>
                                                <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                <td class="text-center"><?php echo $tr['v_periodo'] ?></td>

                                                <td class='text-center'>
                                                    <a href="<?php echo BASE_URL ?>/<?php echo $tr['v_firma'] ?>" target="_blank" class='btn btn-primary btn-sm text-white'>
                                                        <i class='fa fa-file-image'></i>
                                                    </a>
                                                </td>
                                                <td class="text-center">
                                                    <a><span class="badge bg-<?php echo $tr['v_color_estado'] ?>"><?php echo $tr['v_estado'] ?></span></a>
                                                </td>
                                                <td class="text-center"><?php echo $tr['v_lupd_user'] ?></td>
                                                <td class="text-center"><?php echo $tr['d_lupd_date'] ?></td>

                                                <td class='text-center'>
                                                    <a id="<?php echo $tr['i_id'] ?>" nombre="<?php echo $tr['v_periodo'] ?>" estado="<?php echo $tr['v_firma'] ?>" class="btn btn-warning btn-sm editar" style="color:white">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                </td>
                                                <td class='text-center'>
                                                    <a class='btn btn-danger btn-sm text-white eliminar'>
                                                        <i class='fa fa-trash-alt'></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                </tbody>
                            </table>

                        </div>

                    </div>

                </section>

            </div>

        </div>
    </section>

</div>

<!-- MODAL AGREGAR PERFIL-->
<div class="modal fade" id="modal-agregar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">CREAR PERFIL</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Nombre perfil:</label>
                        <input type="text" id="xnombre" tabindex="1" class="form-control" autocomplete="off" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="xbtnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="xbtncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- MODAL EDITAR DATO-->
<div class="modal fade" id="modal-editar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">ACTUALIZAR PERFIL:&nbsp;</h5><b><span id="idtabla"></span></b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Códgo perfil:</label>
                        <input type="text" id="codigo" tabindex="1" class="form-control" autocomplete="off" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Nombre perfil:</label>
                        <input type="text" id="nombre" tabindex="1" class="form-control" autocomplete="off" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Estado:</label>
                        <select id="estado" tabindex="2" class="form-control form-control-md">
                            <option value="0">Inactivo</option>
                            <option value="1">Activo</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="btnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="btncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>